### ISSUE TITLE
Plotting error

### ISSUE THREAD

**Issue by ghost** [iot-lab/oml-plot-tools#5]
Running the tutorial of Radio monitoring for M3 nodes gives me an error while plotting because even though i can visually see seven columns, but the code only sees five columns and hence gives an error. Can someone please help!

The error i receive is:
 /usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py:1769: ConversionWarning: Some errors were detected !
    Line #381121 (got 5 columns instead of 7)
  warnings.warn(errmsg, ConversionWarning)
Traceback (most recent call last):
  File "/usr/local/bin/plot_oml_radio", line 24, in <module>
    oml_plot_tools.radio.main()
  File "/usr/local/lib/python2.7/dist-packages/oml_plot_tools/radio.py", line 162, in main
    radio_plot(data, opts.title, selection)
  File "/usr/local/lib/python2.7/dist-packages/oml_plot_tools/radio.py", line 103, in radio_plot
    oml_plot_rssi(data, title)
  File "/usr/local/lib/python2.7/dist-packages/oml_plot_tools/radio.py", line 140, in oml_plot_rssi
    plt.figure()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 435, in figure
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1813, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by fsaintma** [comment]
Hi it seems that you launch the script on the SSH frontend and you need to export your display. For this purpose you must use this command to connect to the frontend: ssh -X <site>.iot-lab.info.
Say me if it's work ?

**Comment by Hikaru2017** [comment]
> Hi it seems that you launch the script on the SSH frontend and you need to export your display. For this purpose you must use this command to connect to the frontend: ssh -X .iot-lab.info.
> Say me if it's work ?

hi fsaintma,
I also met the same issues, and I believe I used ssh -X .iot-lab.info. 
it does not work. 
thanks.

**Comment by rienafairefr** [comment]
@anonyette I think there is a transient issue that is normal: 
If you try to plot OML files that are currently being written, it's normal (and likely) that the file will be truncated in the middle of a line, the last 'line' will be partial. But oml plot tools are able to cope with that normally. The loading of the file can take quite some time depending on the number of lines, also.
the $DISPLAY error comes from forgetting the `ssh -X`, that's for sure :-)
